services:
    mpm:
        image: cswni/frankenphp:0.0.1
        env_file:
            - /var/www/apps/mpm/web/.env
        ports:
            - ${APP_PORT:-8082}:8000
        volumes:
            - /var/www/apps/mpm/web:/var/www/html
            #- ./vendor/:${WORKDIR}/vendor
        networks:
            - traefik-net
networks:
    traefik-net:
      external: true
